# Data Manipulation with Pandas

### Import Pandas

In [2]:
import pandas as pd

### Pandas Data Manipulation:
It is the process of changing, organizing, or filtering data using the Pandas library in Python.

### Read CSV File

In [3]:
df = pd.read_csv("Data Science.csv")

### Show top 5 Row

In [4]:
df = pd.read_csv("Data Science.csv")
df.head()

,Student_ID,Name,Age,Gender,Department,Year,CGPA,Email,Phone_Number,Address
0,1,Zeeshan Bumb,24,Female,Electronics,Third,6.15,kuriantarini@dora-sama.org,919938798828,"H.No. 26, Sarma Street, Ambarnath 906793"
1,2,Stuvan Raman,21,Female,Electrical,Fourth,7.50,faiyaz65@wason-buch.org,910749906732,"H.No. 870, Dar Path, Bihar Sharif-934992"
2,3,Trisha Bedi,22,Male,Electronics,Fourth,7.86,siya05@hotmail.com,5205753692,"H.No. 82, Agarwal Ganj, Jalna-079311"
3,4,Samiha Dasgupta,24,Female,Civil,Second,8.84,nirvaanatwal@sankar.com,9699519489,"69/218, Gill Path, Bhind 579676"
4,5,Gatik Sidhu,20,Male,Electronics,Fourth,5.22,ira32@hotmail.com,7205460937,"45, Dhawan Chowk, Kota 223269"

###  Drop Null Values

In [10]:
df = df.dropna()           # # Remove missing values from dataset
df.head()

,Student_ID,Name,Age,Gender,Department,Year,CGPA,Email,Phone_Number,Address
0,1,Zeeshan Bumb,24,Female,Electronics,Third,6.15,kuriantarini@dora-sama.org,919938798828,"H.No. 26, Sarma Street, Ambarnath 906793"
1,2,Stuvan Raman,21,Female,Electrical,Fourth,7.50,faiyaz65@wason-buch.org,910749906732,"H.No. 870, Dar Path, Bihar Sharif-934992"
2,3,Trisha Bedi,22,Male,Electronics,Fourth,7.86,siya05@hotmail.com,5205753692,"H.No. 82, Agarwal Ganj, Jalna-079311"
3,4,Samiha Dasgupta,24,Female,Civil,Second,8.84,nirvaanatwal@sankar.com,9699519489,"69/218, Gill Path, Bhind 579676"
4,5,Gatik Sidhu,20,Male,Electronics,Fourth,5.22,ira32@hotmail.com,7205460937,"45, Dhawan Chowk, Kota 223269"

### Check actual column names in the dataset

In [17]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Year', 'CGPA',
       'Email', 'Phone_Number', 'Address'],
      dtype='object')

###  Add New Column – Double CGPA

In [22]:
df['Double_CGPA'] = df['CGPA'] * 2         #  Add a new column 'Double_CGPA' by multiplying CGPA by 2

df.head()

,Student_ID,Name,Age,Gender,Department,Year,CGPA,Email,Contact,Address,Double_CGPA
0,1,Zeeshan Bumb,24,Female,Electronics,Third,6.15,kuriantarini@dora-sama.org,919938798828,"H.No. 26, Sarma Street, Ambarnath 906793",12.30
1,2,Stuvan Raman,21,Female,Electrical,Fourth,7.50,faiyaz65@wason-buch.org,910749906732,"H.No. 870, Dar Path, Bihar Sharif-934992",15.00
2,3,Trisha Bedi,22,Male,Electronics,Fourth,7.86,siya05@hotmail.com,5205753692,"H.No. 82, Agarwal Ganj, Jalna-079311",15.72
3,4,Samiha Dasgupta,24,Female,Civil,Second,8.84,nirvaanatwal@sankar.com,9699519489,"69/218, Gill Path, Bhind 579676",17.68
4,5,Gatik Sidhu,20,Male,Electronics,Fourth,5.22,ira32@hotmail.com,7205460937,"45, Dhawan Chowk, Kota 223269",10.44

### Rename Column – 'Phone_Number' to 'Contact'

In [21]:
df.rename(columns={'Phone_Number': 'Contact'}, inplace=True)          #  Rename the column 'Phone_Number' to 'Contact'

df.head()

,Student_ID,Name,Age,Gender,Department,Year,CGPA,Email,Contact,Address,Double_CGPA
0,1,Zeeshan Bumb,24,Female,Electronics,Third,6.15,kuriantarini@dora-sama.org,919938798828,"H.No. 26, Sarma Street, Ambarnath 906793",12.30
1,2,Stuvan Raman,21,Female,Electrical,Fourth,7.50,faiyaz65@wason-buch.org,910749906732,"H.No. 870, Dar Path, Bihar Sharif-934992",15.00
2,3,Trisha Bedi,22,Male,Electronics,Fourth,7.86,siya05@hotmail.com,5205753692,"H.No. 82, Agarwal Ganj, Jalna-079311",15.72
3,4,Samiha Dasgupta,24,Female,Civil,Second,8.84,nirvaanatwal@sankar.com,9699519489,"69/218, Gill Path, Bhind 579676",17.68
4,5,Gatik Sidhu,20,Male,Electronics,Fourth,5.22,ira32@hotmail.com,7205460937,"45, Dhawan Chowk, Kota 223269",10.44

### Filter students with Age > 22

In [23]:
filtered_df = df[df['Age'] > 22]                     # Filter students older than 22 years

filtered_df.head()

,Student_ID,Name,Age,Gender,Department,Year,CGPA,Email,Contact,Address,Double_CGPA
0,1,Zeeshan Bumb,24,Female,Electronics,Third,6.15,kuriantarini@dora-sama.org,919938798828,"H.No. 26, Sarma Street, Ambarnath 906793",12.30
3,4,Samiha Dasgupta,24,Female,Civil,Second,8.84,nirvaanatwal@sankar.com,9699519489,"69/218, Gill Path, Bhind 579676",17.68
7,8,Zoya Kata,24,Male,Civil,Fourth,6.40,rhea72@bajaj.com,9048094588,"45, Choudhry Marg, Bareilly-676006",12.80
10,11,Ishita Sawhney,24,Female,Electronics,First,9.77,lsehgal@yahoo.com,8327543863,"H.No. 865, Rajagopalan Zila, Muzaffarnagar-609120",19.54
16,17,Azad Sura,23,Female,Civil,Fourth,6.53,shalv82@bal.info,2819638644,"77, Jha Chowk, Gwalior-756223",13.06

### Sort data by CGPA in descending order

In [25]:
df = df.sort_values(by='CGPA', ascending=False)            # Cell 9: Sort dataframe by CGPA in descending order

df.head()

,Student_ID,Name,Age,Gender,Department,Year,CGPA,Email,Contact,Address,Double_CGPA
5,6,Indrajit Kala,22,Female,Electrical,First,9.97,ratishetty@gmail.com,219601813,"34, Basak, Mahbubnagar-243823",19.94
53,54,Bhavin Setty,22,Male,Computer Science,Second,9.91,akarsh69@lal-kakar.com,910313908199,"02/73, Vala Path, Darbhanga-740154",19.82
14,15,Nitya Lal,21,Female,Civil,First,9.90,shray68@bawa.com,4610177935,"092, Gokhale Ganj, Gwalior-838545",19.80
71,72,Raghav Goel,24,Male,Mechanical,First,9.85,hbanik@bera.com,5473024113,"H.No. 70, Brahmbhatt Nagar, Danapur 309706",19.70
63,64,Kartik Bhatti,18,Female,Civil,First,9.83,lakshit88@yahoo.com,9221365574,"839, Chauhan Zila, Loni-222955",19.66

### Group by Department and calculate average CGPA

In [5]:
grouped = df.groupby('Department')['CGPA'].mean()             #  Group data by Department and get average CGPA
grouped.head()

Department
Civil               6.867500
Computer Science    7.304615
Electrical          7.181739
Electronics         6.854167
Mechanical          8.003333
Name: CGPA, dtype: float64